import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { SessionProvider } from "@/providers/SessionProvider";
import { authOptions } from "@/libs/authOptions";
import ClientProviders from "./providers";
import Sidebar from "@/components/Layout/Sidebar";

const font = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(
    authOptions
  );
  return (
    <html lang="en">
      <body className={font.className + " bg-black text-white"}>
        <SessionProvider session={session}
          basePath="/api/auth"
        >
          <ClientProviders>
            <main className='flex h-screen w-full gap-4'>
              <Sidebar />
              <div className="flex flex-col items-center justify-center w-full h-screen overflow-y-auto">{children}</div>
            </main>
          </ClientProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
