import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { SessionProvider } from "@/providers/SessionProvider";
import { authOptions } from "@/libs/authOptions";
import ClientProviders from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(
    authOptions
  );
  return (
    <html lang="en">
      <body className={inter.className + " h-full w-ull"}>
        <SessionProvider session={session}
          basePath="/api/auth"
        >
          <ClientProviders>
            <main className='flex flex-col justify-center items-center min-h-screen w-full bg-black text-white'>
              {children}
            </main>
          </ClientProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
